import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "PulseIQ — AI-Driven Consumer Insights Platform",
  description:
    "Analyze consumer behavior, predict market trends, and generate actionable marketing insights with agentic AI.",
};

const FEATURES = [
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
      </svg>
    ),
    title: "Real-Time Analytics",
    description: "Funnels, cohort analysis, and behavioral heatmaps updated as your data flows in.",
  },
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" />
      </svg>
    ),
    title: "Trend Prediction",
    description: "GPT-4o forecasts emerging product and market trends before your competitors spot them.",
  },
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
      </svg>
    ),
    title: "Sentiment Analysis",
    description: "Classify thousands of customer reviews in seconds — positive, neutral, or negative — with confidence scores.",
  },
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
      </svg>
    ),
    title: "AI Recommendations",
    description: "Prioritized, org-specific marketing and sales actions generated by your data — not generic advice.",
  },
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 018.25 20.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z" />
      </svg>
    ),
    title: "Custom Dashboards",
    description: "Drag-and-drop KPI dashboards with drill-downs, real-time updates, and role-based visibility.",
  },
  {
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
      </svg>
    ),
    title: "Secure & Multi-Tenant",
    description: "RBAC, JWT auth, SSO, row-level data isolation, and full GDPR audit trails — built in from day one.",
  },
];

const STATS = [
  { value: "4", label: "AI Agents" },
  { value: "GPT-4o", label: "Powered by" },
  { value: "4", label: "User Roles" },
  { value: "GDPR", label: "Compliant" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#F3F2EF]">
      {/* Top nav */}
      <header className="bg-white border-b border-[#D9D8D3] sticky top-0 z-40">
        <div className="max-w-[1280px] mx-auto px-6 h-14 flex items-center justify-between">
          <span className="text-[18px] font-bold text-[#0A66C2] tracking-tight">
            PulseIQ
          </span>
          <nav className="hidden md:flex items-center gap-6 text-[14px] text-[#4A4A4A]">
            <a href="#features" className="hover:text-[#0A66C2] transition-colors">Features</a>
            <a href="#how-it-works" className="hover:text-[#0A66C2] transition-colors">How it works</a>
            <a href="#roles" className="hover:text-[#0A66C2] transition-colors">Roles</a>
          </nav>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="text-[14px] font-medium text-[#0A66C2] hover:text-[#004182] transition-colors"
            >
              Sign in
            </Link>
            <Link
              href="/register"
              className="h-9 px-4 inline-flex items-center rounded-[6px] bg-[#0A66C2] text-white text-[14px] font-medium hover:bg-[#004182] transition-colors"
            >
              Get started
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-[1280px] mx-auto px-6 pt-20 pb-16 text-center">
        <div className="inline-flex items-center gap-2 bg-[#7C3AED]/10 border border-[#7C3AED]/20 rounded-full px-4 py-1.5 mb-6">
          <span className="h-2 w-2 rounded-full bg-[#7C3AED]" aria-hidden="true" />
          <span className="text-[13px] font-medium text-[#7C3AED]">
            Powered by GPT-4o Agentic AI
          </span>
        </div>
        <h1 className="text-[48px] md:text-[56px] font-bold text-[#1A1A1A] leading-tight tracking-tight max-w-3xl mx-auto mb-6">
          Consumer Insights,{" "}
          <span className="text-[#0A66C2]">Driven by AI</span>
        </h1>
        <p className="text-[18px] text-[#4A4A4A] max-w-xl mx-auto mb-10 leading-relaxed">
          PulseIQ helps e-commerce and retail businesses understand customer
          behavior, predict trends, and act on AI-generated recommendations —
          all from one platform.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link
            href="/register"
            className="h-11 px-8 inline-flex items-center rounded-[6px] bg-[#0A66C2] text-white text-[15px] font-medium hover:bg-[#004182] transition-colors shadow-sm"
          >
            Start for free
          </Link>
          <Link
            href="/dashboard"
            className="h-11 px-8 inline-flex items-center rounded-[6px] bg-white border border-[#D9D8D3] text-[#1A1A1A] text-[15px] font-medium hover:bg-[#F3F2EF] transition-colors"
          >
            View demo dashboard →
          </Link>
        </div>
      </section>

      {/* Stats bar */}
      <section className="bg-white border-y border-[#D9D8D3]">
        <div className="max-w-[1280px] mx-auto px-6 py-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {STATS.map((stat) => (
              <div key={stat.label}>
                <p className="text-[32px] font-bold text-[#0A66C2]">{stat.value}</p>
                <p className="text-[13px] text-[#8A8A8A] mt-1">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="max-w-[1280px] mx-auto px-6 py-20">
        <div className="text-center mb-12">
          <h2 className="text-[32px] font-bold text-[#1A1A1A] mb-3">
            Everything you need to understand your customers
          </h2>
          <p className="text-[16px] text-[#4A4A4A] max-w-lg mx-auto">
            Six core capabilities, powered by agentic AI, working together in one platform.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((feature) => (
            <div
              key={feature.title}
              className="bg-white rounded-lg border border-[#D9D8D3] p-6 shadow-[0_1px_3px_rgba(0,0,0,0.08)] hover:shadow-[0_4px_12px_rgba(0,0,0,0.08)] transition-shadow"
            >
              <div className="h-10 w-10 rounded-lg bg-[#0A66C2]/10 flex items-center justify-center text-[#0A66C2] mb-4">
                {feature.icon}
              </div>
              <h3 className="text-[15px] font-semibold text-[#1A1A1A] mb-2">
                {feature.title}
              </h3>
              <p className="text-[14px] text-[#4A4A4A] leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="bg-white border-y border-[#D9D8D3] py-20">
        <div className="max-w-[1280px] mx-auto px-6">
          <div className="text-center mb-12">
            <h2 className="text-[32px] font-bold text-[#1A1A1A] mb-3">How it works</h2>
            <p className="text-[16px] text-[#4A4A4A] max-w-lg mx-auto">
              From raw data to actionable insight in four steps.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative">
            {[
              { step: "1", title: "Ingest", desc: "Push sales, product, and customer data via REST API or CSV upload." },
              { step: "2", title: "Process", desc: "ETL pipeline validates, transforms, and normalizes your data automatically." },
              { step: "3", title: "Analyze", desc: "Agentic AI agents run behavior analysis, sentiment scoring, and trend forecasting." },
              { step: "4", title: "Act", desc: "Prioritized recommendations appear on your dashboard — ready to execute." },
            ].map((item, i) => (
              <div key={item.step} className="relative text-center">
                {i < 3 && (
                  <div className="hidden md:block absolute top-5 left-[60%] w-[80%] h-px bg-[#D9D8D3]" aria-hidden="true" />
                )}
                <div className="inline-flex items-center justify-center h-10 w-10 rounded-full bg-[#0A66C2] text-white text-[14px] font-bold mb-4">
                  {item.step}
                </div>
                <h3 className="text-[15px] font-semibold text-[#1A1A1A] mb-2">{item.title}</h3>
                <p className="text-[13px] text-[#4A4A4A] leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Roles */}
      <section id="roles" className="max-w-[1280px] mx-auto px-6 py-20">
        <div className="text-center mb-12">
          <h2 className="text-[32px] font-bold text-[#1A1A1A] mb-3">Built for every team member</h2>
          <p className="text-[16px] text-[#4A4A4A] max-w-lg mx-auto">
            Role-based access ensures every person sees exactly what they need.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            { role: "Admin", color: "#0A66C2", desc: "Full platform access — user management, data sources, API keys, audit logs, and org settings." },
            { role: "Analyst", color: "#2D9E6B", desc: "Dashboards, behavior analytics, trend predictions, AI insights, and sentiment results." },
            { role: "Marketer", color: "#E8940A", desc: "AI recommendations, sentiment summaries, and data export — focused on action." },
            { role: "Viewer", color: "#6B7280", desc: "Read-only access to assigned dashboards. Perfect for executives and stakeholders." },
          ].map((item) => (
            <div key={item.role} className="bg-white rounded-lg border border-[#D9D8D3] p-6 shadow-[0_1px_3px_rgba(0,0,0,0.08)]">
              <span
                className="inline-block px-3 py-1 rounded-full text-[12px] font-semibold text-white mb-4"
                style={{ backgroundColor: item.color }}
              >
                {item.role}
              </span>
              <p className="text-[14px] text-[#4A4A4A] leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#0A66C2] py-16">
        <div className="max-w-[1280px] mx-auto px-6 text-center">
          <h2 className="text-[32px] font-bold text-white mb-4">
            Ready to understand your customers?
          </h2>
          <p className="text-[16px] text-white/80 mb-8 max-w-md mx-auto">
            Connect your data source and get your first AI insights in minutes.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center h-11 px-8 rounded-[6px] bg-white text-[#0A66C2] text-[15px] font-semibold hover:bg-[#F3F2EF] transition-colors"
          >
            Get started free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-white border-t border-[#D9D8D3] py-8">
        <div className="max-w-[1280px] mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-[18px] font-bold text-[#0A66C2]">PulseIQ</span>
          <p className="text-[13px] text-[#8A8A8A]">
            &copy; {new Date().getFullYear()} PulseIQ. All rights reserved.
          </p>
          <div className="flex items-center gap-6 text-[13px] text-[#4A4A4A]">
            <a href="#" className="hover:text-[#0A66C2] transition-colors">Privacy</a>
            <a href="#" className="hover:text-[#0A66C2] transition-colors">Terms</a>
            <Link href="/login" className="hover:text-[#0A66C2] transition-colors">Sign in</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
