from .health import router as health_router
from .auth import router as auth_router
from .users import router as users_router
from .ingestion import router as ingestion_router
from .analytics import router as analytics_router
from .insights import router as insights_router
from .sentiment import router as sentiment_router
from .dashboards import router as dashboards_router
from .export import router as export_router
from .mobile import router as mobile_router
from .admin import router as admin_router
