"use client";

import Link from "next/link";
import { useDashboardSummary } from "@/hooks/useDashboardSummary";
import { Skeleton } from "@/components/ui/Skeleton";

interface RiskBarProps {
  label: string;
  count: number;
  total: number;
  color: string;
  textColor: string;
}

function RiskBar({ label, count, total, color, textColor }: RiskBarProps) {
  const pct = total > 0 ? (count / total) * 100 : 0;
  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <div className="flex items-center gap-1.5">
          <span className="w-2 h-2 rounded-full inline-block flex-shrink-0" style={{ backgroundColor: color }} />
          <span className="text-[12px] text-[#4A4A4A]">{label}</span>
        </div>
        <span className="text-[13px] font-semibold" style={{ color: textColor }}>{count.toLocaleString()}</span>
      </div>
      <div className="h-2 rounded-full bg-[#EAE9E4] overflow-hidden">
        <div
          className="h-full rounded-full transition-all duration-700"
          style={{ width: `${pct}%`, backgroundColor: color }}
          role="progressbar"
          aria-valuenow={Math.round(pct)}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label={`${label}: ${count}`}
        />
      </div>
    </div>
  );
}

export function ChurnRiskSnapshot() {
  const { data, isLoading, error } = useDashboardSummary();

  if (isLoading) {
    return (
      <div className="bg-white border border-[#D9D8D3] rounded-xl p-5 shadow-sm">
        <Skeleton className="h-4 w-36 mb-4" />
        <div className="space-y-3">
          <Skeleton className="h-6 w-full" />
          <Skeleton className="h-6 w-full" />
          <Skeleton className="h-6 w-full" />
        </div>
      </div>
    );
  }

  const churn = data?.churn_risk ?? { high: 0, medium: 0, low: 0, total: 0 };
  const noData = churn.total === 0;

  return (
    <div className="bg-white border border-[#D9D8D3] rounded-xl p-5 shadow-sm">
      <div className="flex items-start justify-between mb-4">
        <div>
          <h3 className="text-[15px] font-semibold text-[#1A1A1A]">Churn Risk</h3>
          <p className="text-[12px] text-[#8A8A8A] mt-0.5">AI-identified customers at risk</p>
        </div>
        <Link
          href="/insights"
          className="text-[12px] text-[#0A66C2] hover:text-[#004182] font-medium transition-colors flex-shrink-0"
        >
          Details →
        </Link>
      </div>

      {noData ? (
        <div className="text-center py-4">
          <div className="text-[28px] mb-1">—</div>
          <p className="text-[12px] text-[#8A8A8A]">No churn signals detected yet</p>
        </div>
      ) : (
        <>
          <div className="flex items-baseline gap-1 mb-4">
            <span className="text-[32px] font-bold text-[#1A1A1A] leading-none">
              {churn.total.toLocaleString()}
            </span>
            <span className="text-[13px] text-[#8A8A8A]">at-risk signals</span>
          </div>

          <div className="space-y-3">
            <RiskBar
              label="High risk"
              count={churn.high}
              total={churn.total}
              color="#CC3333"
              textColor="#CC3333"
            />
            <RiskBar
              label="Medium risk"
              count={churn.medium}
              total={churn.total}
              color="#E8940A"
              textColor="#E8940A"
            />
            <RiskBar
              label="Low risk"
              count={churn.low}
              total={churn.total}
              color="#6B7280"
              textColor="#6B7280"
            />
          </div>
        </>
      )}

      {!noData && (
        <p className="text-[11px] text-[#8A8A8A] mt-3 border-t border-[#EAE9E4] pt-2">
          Generated by ChurnAgent · GPT-4o
        </p>
      )}
    </div>
  );
}
